imcntk_files=(
  "nl/uva/imcn/libraries/BasicDemonsWarping.java"
  "nl/uva/imcn/libraries/BasicRigidRegistration.java"
  "nl/uva/imcn/libraries/BinaryTopology.java"
  "nl/uva/imcn/libraries/Gdm3d.java"
  "nl/uva/imcn/libraries/ImageFilters.java"
  "nl/uva/imcn/libraries/ImageGeometry.java"
  "nl/uva/imcn/libraries/ImageInterpolation.java"
  "nl/uva/imcn/libraries/ImageStatistics.java"
  "nl/uva/imcn/libraries/ObjectExtraction.java"
  "nl/uva/imcn/libraries/ObjectGeometry.java"
  "nl/uva/imcn/libraries/ObjectLabeling.java"
  "nl/uva/imcn/libraries/ObjectMorphology.java"
  "nl/uva/imcn/libraries/ObjectStatistics.java"
  "nl/uva/imcn/libraries/ObjectTransforms.java"
  "nl/uva/imcn/libraries/ParametricTransform.java"

 "nl/uva/imcn/methods/InflateGdm.java"
  "nl/uva/imcn/methods/MaxProbaRepresentation.java"
  "nl/uva/imcn/methods/MgdmRepresentation.java"
  "nl/uva/imcn/methods/MinMaxFiltering.java"
  "nl/uva/imcn/methods/SmoothGdm.java"
  "nl/uva/imcn/methods/SpatialImageDiffusion.java"
  "nl/uva/imcn/methods/StatisticalUncertaintyReduction.java"

  "nl/uva/imcn/structures/BinaryHeap2D.java"
  "nl/uva/imcn/structures/BinaryHeap3D.java"
  "nl/uva/imcn/structures/BinaryHeapPair.java"
  "nl/uva/imcn/structures/BinaryTree.java"
  "nl/uva/imcn/structures/CriticalPointLUT.java"
  "nl/uva/imcn/structures/RotationMatrix.java"

  "nl/uva/imcn/utilities/Matrix3D.java"
  "nl/uva/imcn/utilities/Ngb.java"
  "nl/uva/imcn/utilities/Numerics.java"
)